user_profile = {
    "title": "Mr.",
    "first_name": "John",
    "middle_initial": "A",
    "last_name": "Doe",
    "full_name": "John A Doe",
    "company": "Example Inc.",
    "position": "Developer",
    "address_line1": "123 Main St",
    "address_line2": "Suite 456",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "zip": "10001",
    "home_phone": "123-456-7890",
    "work_phone": "123-555-7890",
    "fax": "123-555-0000",
    "cell_phone": "987-654-3210",
    "email": "john.doe@example.com",
    "website": "https://example.com",
    "user_id": "johndoe123",
    "password": "strongPassword123",
    "credit_card_type": "Visa",
    "credit_card_number": "4111111111111111",
    "card_verification_code": "123",
    "card_expiration_month": "01",
    "card_expiration_year": "2027",
    "card_user_name": "John A Doe",
    "card_issuing_bank": "Bank of Example",
    "sex": "Male",
    "social_security_number": "123-45-6789",
    "driver_license_number": "D1234567",
    "dob_month": "01",
    "dob_day": "01",
    "dob_year": "1990",
    "age": 33,
    "birth_place": "New York",
    "income": "100000",
    "custom_message": "Hello, this is a test entry.",
    "comments": "No comments"
}
